{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "js5server",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-1.0.1.jar",
          "url": "js5server-1.0.1.jar",
          "size": 61569,
          "sha512": "52c3d3bddc20a66ccee441fe71a57da637cef87484dcd33d5356d0ccc53de906b558e3fe2ec4befaf78ba00a3092c81104a127177998813207a2a58a1ddd8edc",
          "sha256": "5e9b9531ecc342a3c547ef2a021f16a4de2fb1825eef673add5ed37a61a594a3",
          "sha1": "1af20296f47e6316fa39d0badb4caf0efdbadc49",
          "md5": "4e505c19a95367bfbf74b0a501ce639d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.12"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.107.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-transport-native-io_uring",
          "version": {
            "requires": "0.0.25.Final"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "org.jctools",
          "module": "jctools-core",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "js5server-1.0.1.jar",
          "url": "js5server-1.0.1.jar",
          "size": 61569,
          "sha512": "52c3d3bddc20a66ccee441fe71a57da637cef87484dcd33d5356d0ccc53de906b558e3fe2ec4befaf78ba00a3092c81104a127177998813207a2a58a1ddd8edc",
          "sha256": "5e9b9531ecc342a3c547ef2a021f16a4de2fb1825eef673add5ed37a61a594a3",
          "sha1": "1af20296f47e6316fa39d0badb4caf0efdbadc49",
          "md5": "4e505c19a95367bfbf74b0a501ce639d"
        }
      ]
    }
  ]
}
