{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "injector-plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-1.0.1.jar",
          "url": "injector-plugin-1.0.1.jar",
          "size": 493579,
          "sha512": "f2521615994277df961269576d10f6ae2c4169eb32e23cfc4ad2559ad0f499d9dfd4ec62ed33c52f7c5aa9b0a9d1ee1f204a6350c274e23a4a28b66c6157a06b",
          "sha256": "21c2bec2df0a052e99b8448a87a97858369ef7277efb11c83a2be63b40ba2beb",
          "sha1": "f6b3458175f8fa435c7740d3ad9016609daab112",
          "md5": "41cbef357788c9c29a89ad4ac38d2b6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-1.0.1.jar",
          "url": "injector-plugin-1.0.1.jar",
          "size": 493579,
          "sha512": "f2521615994277df961269576d10f6ae2c4169eb32e23cfc4ad2559ad0f499d9dfd4ec62ed33c52f7c5aa9b0a9d1ee1f204a6350c274e23a4a28b66c6157a06b",
          "sha256": "21c2bec2df0a052e99b8448a87a97858369ef7277efb11c83a2be63b40ba2beb",
          "sha1": "f6b3458175f8fa435c7740d3ad9016609daab112",
          "md5": "41cbef357788c9c29a89ad4ac38d2b6c"
        }
      ]
    }
  ]
}
