{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.2.4.jar",
          "url": "filestore-1.2.4.jar",
          "size": 271660,
          "sha512": "d7f2fbfcf0e274afb1a74ad4037878e94c339463665e73424dd5bedca9e2cbd679c66e6b5ed3147ee497578ce74c32d351bf5b7cfa56872e1001f7268c9b9301",
          "sha256": "a95255b3613c3c232d9c4809c3cec7538bd208f32e91965d0d77044eabcbd0aa",
          "sha1": "6ce7d612622f72c7700f4dc6185b09c7fe86c6b2",
          "md5": "b8c3e84538fb373366dd9603325915d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.1.0-alpha1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "net.lingala.zip4j",
          "module": "zip4j",
          "version": {
            "requires": "2.11.5"
          }
        },
        {
          "group": "dev.openrune",
          "module": "js5server",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.2.4.jar",
          "url": "filestore-1.2.4.jar",
          "size": 271660,
          "sha512": "d7f2fbfcf0e274afb1a74ad4037878e94c339463665e73424dd5bedca9e2cbd679c66e6b5ed3147ee497578ce74c32d351bf5b7cfa56872e1001f7268c9b9301",
          "sha256": "a95255b3613c3c232d9c4809c3cec7538bd208f32e91965d0d77044eabcbd0aa",
          "sha1": "6ce7d612622f72c7700f4dc6185b09c7fe86c6b2",
          "md5": "b8c3e84538fb373366dd9603325915d2"
        }
      ]
    }
  ]
}
