{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "injector-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-1.0.0.jar",
          "url": "injector-plugin-1.0.0.jar",
          "size": 493932,
          "sha512": "bd4cd065da072165f005a36859bda8476e222ebf80f597e4fd61c9fe0cc53cd648f049e8ee9dc784a25e937e0e7d3ee8c03c5218ff975d5aa5eb7aab25aeaf3a",
          "sha256": "6194ffba467ce817fdb81c4032c775bc61186461a88ef881d65e77546b9b21b7",
          "sha1": "a7daa0f9b76060b9994d1e01c25ed58176426179",
          "md5": "9a1673d24ce1a62a7cdd7b56389d7824"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-1.0.0.jar",
          "url": "injector-plugin-1.0.0.jar",
          "size": 493932,
          "sha512": "bd4cd065da072165f005a36859bda8476e222ebf80f597e4fd61c9fe0cc53cd648f049e8ee9dc784a25e937e0e7d3ee8c03c5218ff975d5aa5eb7aab25aeaf3a",
          "sha256": "6194ffba467ce817fdb81c4032c775bc61186461a88ef881d65e77546b9b21b7",
          "sha1": "a7daa0f9b76060b9994d1e01c25ed58176426179",
          "md5": "9a1673d24ce1a62a7cdd7b56389d7824"
        }
      ]
    }
  ]
}
