{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.openrune",
    "module": "filestore",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.0.0.jar",
          "url": "filestore-1.0.0.jar",
          "size": 178809,
          "sha512": "ff3375c9672bc4e3d86a7a28382d8a547537c58dbc3e28228589f2c1582f7841e1334001c6d6df17293801f456ae66888f89da9ee2d7a8b9c1d0ea6630ae59f7",
          "sha256": "e0591f911ddb95e33d142c92403fddb7a4866dd8841eebd6f92b320af9f878ef",
          "sha1": "e5b8126028cb14ee97e90e62c2c0f7545e4c532f",
          "md5": "190d425fb7256f065fc6aad0cfa89876"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "me.tongfei",
          "module": "progressbar",
          "version": {
            "requires": "0.9.2"
          }
        },
        {
          "group": "com.displee",
          "module": "rs-cache-library",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "filestore-1.0.0.jar",
          "url": "filestore-1.0.0.jar",
          "size": 178809,
          "sha512": "ff3375c9672bc4e3d86a7a28382d8a547537c58dbc3e28228589f2c1582f7841e1334001c6d6df17293801f456ae66888f89da9ee2d7a8b9c1d0ea6630ae59f7",
          "sha256": "e0591f911ddb95e33d142c92403fddb7a4866dd8841eebd6f92b320af9f878ef",
          "sha1": "e5b8126028cb14ee97e90e62c2c0f7545e4c532f",
          "md5": "190d425fb7256f065fc6aad0cfa89876"
        }
      ]
    }
  ]
}
